### ISSUE TITLE
Differences from expect-gen?

### ISSUE THREAD

**Issue by akinnee** [neurosnap/gen-tester#2]
👋 Hey Eric! This looks really similar to a tool that Jim already open sourced a while ago.
https://github.com/jimbol/expect-gen

What makes this one different?

**Comment by akinnee** [comment]
Found one major difference so far. `expect-gen` does the assertions for you, while this one returns an actual and expected and leaves how the assertion is made up to the dev. I like that. 👍 I'm going to give it a try.

**Comment by neurosnap** [comment]
Yes that is the main difference.  The other difference is the API.  Instead of chaining methods, I opted for the API to be one function that returns `actual` and `expected` keys.  I also think I was able to simplify some of the library to make it slightly easier to read.

**Comment by akinnee** [comment]
Nice. This is working well so far. Thanks for fixing my issues.
