### ISSUE TITLE
this.equal is undefined

### ISSUE THREAD

**Issue by akinnee** [neurosnap/gen-tester#4]
For `stepsToBeEqual`

**Comment by akinnee** [comment]
Maybe you meant `this.equals`? https://jestjs.io/docs/en/expect#thisequalsa-b

**Comment by akinnee** [comment]
Yeah, that appears to be the case. Workaround:
```
expect.extend({
  stepsToBeEqual: function() {
    return stepsToBeEqual.apply({ ...this, equal: this.equals }, arguments);
  },
});
```

**Comment by neurosnap** [comment]
https://www.npmjs.com/package/gen-tester/v/3.3.0
